name: Package for Windows x64

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create package structure
        run: |
          mkdir -p izarchiv-win-x64/nodejs
          
      - name: Copy application files
        run: |
          xcopy /E /I app izarchiv-win-x64\app
          copy package.json izarchiv-win-x64\
          copy "IZARchiv starten.vbs" "izarchiv-win-x64\IZARchiv starten.vbs"
          
      - name: Install dependencies
        run: |
          cd izarchiv-win-x64
          npm install --production
          
      - name: Download Node.js binary
        run: |
          $nodeVersion = "20.12.1"
          Invoke-WebRequest -Uri "https://nodejs.org/dist/v$nodeVersion/win-x64/node.exe" -OutFile "izarchiv-win-x64\nodejs\node.exe"
          
      - name: Create ZIP archive
        run: |
          Compress-Archive -Path izarchiv-win-x64 -DestinationPath izarchiv-win-x64.zip
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: izarchiv-win-x64
          path: izarchiv-win-x64.zip
          
      - name: Attach to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: izarchiv-win-x64.zip